# Generated by Django 5.1 on 2026-09-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_vendedor_nombre_dw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='subtipo',
            field=models.CharField(blank=True, choices=[('BUG_GENERAL', 'Bug general'), ('ERROR_PERMISOS', 'Error de permisos'), ('ERROR_CALCULO', 'Error de cálculo'), ('ERROR_MEDIDA', 'Error de medida'), ('ERROR_TIPO_VARIABLE', 'Error de tipo de variable'), ('ERROR_VARIACION_MONTO', 'Variación de monto'), ('SOL_NUEVO_CALCULO', 'Solicitud de nuevo cálculo'), ('SOL_AFINACION', 'Solicitud de afinación de medida/cálculo'), ('SOL_NUEVO_DASHBOARD', 'Solicitud de nuevo dashboard')], default='', max_length=30),
        ),
    ]
