# Generated by Django 5.1 on 2026-09-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_reporte_id_alter_reporte_subtipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='listas_precios',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
