# Generated by Django 6.0.3 on 2026-03-15 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.CharField(blank=True, max_length=200, null=True)),
                ('cliente', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
