# Generated by Django 6.0.3 on 2026-03-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'managed': False},
        ),
    ]
