export const CURRENT_VERSION = "1.2.6";

export interface ChangelogVersion {
  version: string;
  date: string;
  fixes: string[];
  features: string[];
  /** perm IDs de dashboards nuevos en esta versión */
  newDashboardPerms: string[];
  /** Nombre legible para cada perm nuevo */
  newDashboardNames: Record<string, string>;
}

export const CHANGELOG: ChangelogVersion[] = [
  {
    version: "1.2.6",
    date: "Junio 2026",
    fixes: [
      "Dashboard Softys: corregido error 500 en KPIs — caracteres % en condiciones LIKE no escapados causaban IndexError en psycopg2 al construir el filtro de universo de clientes por ruta",
      "Dashboard Softys: permisos de Proveedor corregidos — antes quedaban bloqueados a su regional de perfil sin poder cambiarla; ahora pueden navegar entre Nacional y cada regional individualmente",
      "Dashboard Softys: corregido bug en helper _auth_regional_canal — el branch de Proveedor estaba ausente, haciendo que los endpoints de histórico, vendedores y clientes por semana siempre retornaran datos de Santa Cruz en lugar de la regional solicitada",
      "Dashboard Softys (Comparativo Meses): corregido límite de 60 clientes en la tabla comparativa — ahora muestra hasta 500 clientes ordenados por venta total descendente",
    ],
    features: [
      "Dashboard Softys — Reestructuración completa: nueva arquitectura de dos modos de vista (SKUs por Canal y Clientes × Vendedor) con navegación independiente por modo",
      "Dashboard Softys — Vista Clientes × Vendedor: combobox de búsqueda de vendedor con sugerencias en tiempo real al hacer foco o escribir",
      "Dashboard Softys — Vista Clientes × Vendedor: tabla semanal de clientes (sem 1–5) con totales por fila y columna; detalle de SKUs al seleccionar un cliente o semana",
      "Dashboard Softys — Vista Comparativa Meses: tabla de clientes con columna por mes seleccionable (3, 6, 12 meses o rango personalizado); clic en cliente muestra SKUs de todo el rango, clic en celda de mes muestra solo ese mes",
      "Dashboard Softys — Vista Comparativa Meses: tabla de clientes con scroll vertical (máx. 480px) igual que la tabla de SKUs — ya no expande la página infinitamente",
      "Dashboard Softys — Vista Comparativa Meses: encabezado de tabla muestra el nombre del vendedor seleccionado",
      "Dashboard Softys — Subcategorías de Pañales: el filtro de categoría 'Pañales' se expande con dos sub-opciones — Babysec (excluye Packeton) y Packeton — visibles como segunda fila con borde indicador al seleccionar la categoría padre",
      "Dashboard Softys — KPI Cards: métrica de Cobertura reservada para implementación futura (muestra '—' hasta revisión de universo de clientes)",
      "Dashboard Softys — Permisos Proveedor: los usuarios con cargo Proveedor arrancan en vista Nacional y pueden cambiar libremente entre Nacional, Santa Cruz, Cochabamba y La Paz sin poder modificar el filtro de canal",
      "Dashboard Softys — Filtros de período en línea: los controles de período (3M / 6M / 12M / Personalizado) y días comparados se desplazaron al lado del toggle 'Mes Actual / Comparativo Meses' — eliminando la necesidad de scroll para cambiar el rango de comparación",
      "Dashboard Softys — Exportación Excel: botón 'Exportar Excel' descarga los datos crudos del mes seleccionado (fecha, regional, canal, vendedor, cliente, producto, línea Softys, cantidad, venta neta) usando el módulo de descarga estándar del sistema",
      "Navegación: se agrega 'Dashboard Softys (En Revisión)' como ruta separada para revisión interna por gerencia (permiso: softys-nuevo) — el dashboard original de Softys sigue disponible para el proveedor sin cambios",
    ],
    newDashboardPerms: ["softys-nuevo"],
    newDashboardNames: { "softys-nuevo": "Dashboard Softys (En Revisión)" },
  },
  {
    version: "1.2.5",
    date: "Junio 2026",
    fixes: [
      "Seguridad (Supply Chain): react-router-dom actualizado a 7.17.0 (RCE no autenticado + open redirect); vite, picomatch, postcss, brace-expansion actualizados a versiones sin vulnerabilidades conocidas",
      "Seguridad (Autenticación): lockout por fuerza bruta ahora rastrea intentos por username independientemente de IP — cierra bypass vía X-Forwarded-For spoofing",
      "Seguridad (Logging): eventos de seguridad ahora registrados — AUTH_OK, AUTH_FAIL, AUTH_LOCKOUT, ACCESS_DENIED, ADMIN_CREATE_USER, ADMIN_SET_PASSWORD, ADMIN_UPDATE_PERMS",
      "Seguridad: URL de Django admin movida a ruta configurable vía DJANGO_ADMIN_PATH — ya no expuesta en /admin/ predecible",
      "Seguridad: cookies de sesión y CSRF con HttpOnly=True, SameSite=Lax; Secure y HSTS activados automáticamente cuando DEBUG=False",
      "Seguridad: corregido Broken Access Control — Gerente General / Analista de Datos podían crear usuarios y resetear contraseñas; gestión de cuentas ahora restringida a Administrador de Sistema",
      "Seguridad: bloqueada auto-escalada de privilegios — un administrador ya no puede editar su propio cargo ni permisos desde los endpoints de admin",
      "Seguridad: exportaciones XLSX ahora requieren permiso de dashboard (descargas / informacion-rutas); antes cualquier usuario autenticado podía descargarlas",
      "Seguridad: endpoints legacy /dashboard/ventas/ y /dashboard/productos/ ahora requieren permiso 'nacional'; antes eran accesibles por cualquier usuario autenticado",
      "Seguridad: corregido log injection / header injection en _safe_str — el patrón regex \\s permitía \\r\\n en todos los parámetros de texto (canal, supervisor, marca, categoría); reemplazado por espacio literal",
      "Preventas: corregido error 500 para supervisores con canal sin asignar — profile.canal podía ser NULL causando AttributeError",
      "Global: corregido error 500 al inicio de un nuevo mes — todos los dashboards enviaban anho=0&mes=0 antes de cargar el período disponible; se añadió guard que previene cualquier fetch hasta tener año y mes válidos",
      "Comportamiento de Productos: tablas no se generaban aunque los gráficos sí mostraban datos — tres causas: (1) filtros SCD es_vendedor_actual/es_producto_actual excluían históricos, (2) el producto no se auto-seleccionaba al elegir marca, (3) no se enviaba el parámetro regional al backend",
      "Comportamiento de Productos: meses Abr/May/Jun se asignaban incorrectamente a FY27 — corregida fórmula de año fiscal (FY = mes≥4 ? año : año-1)",
      "Comportamiento de Productos: productos no licores mostraban columna «Cajas 9L» — ahora se muestra «Ventas Unidades» para categorías que no son Licores",
      "Ficha de SKU: almacenes de La Paz no aparecían — los valores ciudad en dim_almacen son 'LA PAZ' en mayúsculas, no 'lpz' como se asumía",
      "Ficha de SKU: dropdown de marca abría hacia arriba — reemplazado select nativo por componente custom que siempre abre hacia abajo",
      "Navbar mobile: no se podía hacer scroll ni acceder a perfil/cerrar sesión — overflow-hidden se aplicaba siempre; corregido con overflow-y-auto solo cuando el menú está abierto",
      "Proveedores (dMujer y todos): ventas de productos con proveedor='0' y cat_comercial='DMUJER' quedaban excluidas del dashboard — dMujer mostraba 2 ventas en lugar de 291; corregido filtrando por UPPER(proveedor)=X OR UPPER(cat_comercial)=X en los 3 endpoints (kpis, gráfico, tabla)",
      "Proveedores: gráfico de barras por canal ahora usa el canal del cliente (dual.dim_cliente_dual) en lugar del canal del vendedor — refleja correctamente WHS, DTS, SPM, CODIS, HORECA, PROV según a quién se vendió",
      "Comportamiento de Productos: exportación XLSX ahora descarga todos los SKUs seleccionados (no solo el visible) en un solo archivo con una hoja por SKU — meses ordenados Ene→Dic, años etiquetados FY26, FY25, etc.",
      "Comportamiento de Productos: exportación XLSX migrada de SheetJS a ExcelJS — colores reales en headers (naranja sección, azul canal, slate totales), variaciones en verde/rojo/gris, celdas mergeadas, alineación y formato numérico #,##0",
    ],
    features: [
      "Nuevo dashboard «Comportamiento de Productos»: gráficos y tablas históricas de ventas (clientes, unidades, cajas 9L según categoría) con filtros de marca, regional y canal",
      "Nuevo dashboard «Lista de Precios» (estructura frontend): tabla con Cód. Interno, Cód. Barra, Categoría, SubCategoría, Marca, Estado, Origen, Producto, Costo, PVP, Margen Bs y Margen % — filtros por gestión, mes, canal, estado y origen",
      "Ficha de SKU: gráfico de inventario muestra «días de cobertura» en eje derecho (stock ÷ promedio diario) — directamente interpretable sin comparar escalas",
      "Ficha de SKU: proyección limitada al fin del período seleccionado — antes se extendía hasta agotar el stock",
      "Ficha de SKU: leyenda personalizada con líneas sólidas/punteadas que refleja el estilo real de cada serie; línea ámbar de alerta de 30 días incluida en leyenda",
      "Ficha de SKU: filtro de almacén dinámico — carga los almacenes desde la BD según la regional seleccionada (Santa Cruz: 2 almacenes, Cochabamba y La Paz: 1 cada uno)",
      "Ficha de SKU: filtro de inventario por almacén wired al backend — query usa JOIN con dim_almacen cuando se selecciona un almacén específico",
      "Ficha de SKU: nuevo filtro de marca — se carga desde la BD y filtra las marcas disponibles según la categoría seleccionada; siempre visible aunque no se elija categoría",
      "Ficha de SKU: selector de producto ahora acepta marca como filtro adicional para acotar el combobox de búsqueda",
      "Nuevo endpoint GET /api/dashboard/almacenes/lista/ — devuelve almacenes activos filtrados por regional",
      "Nuevo endpoint GET /api/dashboard/ficha-sku/marcas/ — devuelve marcas disponibles filtradas por categoría",
    ],
    newDashboardPerms: ["ficha-sku", "distribucion-rutas", "comportamiento-productos", "lista-precios"],
    newDashboardNames: {
      "ficha-sku": "Ficha de SKU",
      "distribucion-rutas": "Distribución de Rutas",
      "comportamiento-productos": "Comportamiento de Productos",
      "lista-precios": "Lista de Precios",
    },
  },
  {
    version: "1.2.4",
    date: "Mayo 2026",
    fixes: [
      "Preventas: solo se muestran vendedores registrados en el DW — se eliminan usuarios del sistema que aparecían incorrectamente",
      "Preventas: valores de monto ya no se redondean, se muestran con 2 decimales reales",
      "Información Rutas: valores de venta (Bs) ya no se redondean en ninguna tabla ni gráfico — se muestran con 2 decimales reales",
    ],
    features: [
      "Dashboard Supervisores: fila «Total día» al pie de la tabla de liquidaciones con la suma de ventas de cada columna de fecha",
      "Dashboard Matriz: datos reales desde el DW reemplazando los datos de demostración — filtros con control de acceso por rol (regional bloqueado para no-administradores)",
      "Información Rutas: gráfico y tabla de tendencia semanal ahora muestran dinámicamente cuántas semanas tiene el mes (4 o 5) con ceros para semanas sin datos",
      "Información Rutas: nueva tabla de clientes con compras semanales por cliente — clic en nombre muestra todo el mes, clic en celda muestra esa semana",
      "Información Rutas: tabla de clientes ahora incluye todos los clientes de la ruta, no solo los que compraron en el período",
      "Información Rutas: panel lateral de detalle de SKUs por cliente (unidades y Bs) al seleccionar un cliente o una semana específica",
      "Información Rutas: código de cliente mostrado como badge junto al nombre para mejor legibilidad en la tabla",
    ],
    newDashboardPerms: [],
    newDashboardNames: {},
  },
  {
    version: "1.2.3",
    date: "Mayo 2026",
    fixes: [
      "Preventas: filtro de fecha corregido para columnas timestamp — ahora un solo día muestra datos correctamente",
      "Gerente Regional: filtros de regional ahora se bloquean correctamente al perfil del usuario en todos los dashboards (Regionales, Canales/Regional, Supervisores, Unidades Supervisores, Información Rutas, Tendencia Estacional, Preventas)",
      "Dashboard Canales/Regional: rol Gerente Regional incorrectamente tratado como administrador — corregido para bloquear regional y permitir libre selección de canal",
      "Dashboard Regionales: agregado control de acceso por rol — Gerente Regional solo puede ver su regional asignada",
      "Supervisores: lista de nombres ahora muestra formato Nombre Apellido en lugar de NOMBRE APELLIDO (INITCAP en backend)",
      "Rutas: tabla siempre ordenada de mayor a menor cobertura sin importar los filtros activos",
    ],
    features: [
      "Tendencia Estacional: nuevo filtro de supervisor con restricciones por rol (igual que los demás dashboards)",
      "Dashboard Supervisores: Gerente Regional puede ver y filtrar por canal y supervisor dentro de su regional",
    ],
    newDashboardPerms: [],
    newDashboardNames: {},
  },
  {
    version: "1.2.2",
    date: "Mayo 2026",
    fixes: ["Preventas: filtro de fecha corregido para columnas timestamp — ahora un solo día muestra datos correctamente"],
    features: ["Preventas: columnas H. Inicio, Últ. Movimiento y T. Trabajado ahora muestran la primera y última transacción del día por vendedor y el tiempo total trabajado"],
    newDashboardPerms: [],
    newDashboardNames: {},
  },
  {
    version: "1.2.1",
    date: "Mayo 2026",
    fixes: ["Dashboard Supervisores: tabla de liquidaciones muestra el monto completo en Bs sin abreviar (antes mostraba formato xxK)"],
    features: [],
    newDashboardPerms: [],
    newDashboardNames: {},
  },
  {
    version: "1.2.0",
    date: "Mayo 2026",
    fixes: [
      "Dashboard Supervisores: tabla resumen y gráfico ahora incluyen la categoría «Sin Clasificar»",
      "Períodos sin datos ya no muestran ceros: si el mes/año seleccionado no existe en el DW se salta automáticamente al período más reciente disponible",
    ],
    features: [
      "Nuevo dashboard «Preventas Realizadas»: seguimiento de pedidos con selector de rango de fechas libre (día, semana, mes o período personalizado)",
      "Gráfico de Preventas con drill-down automático: sin filtros muestra por canal, al seleccionar canal muestra por supervisor, al seleccionar supervisor muestra por vendedor",
      "Tabla de vendedores con colores por monto (verde ≥ Bs 1.500, amarillo ≥ Bs 1.000, naranja ≥ Bs 500, rojo < Bs 500) y ordenamiento por monto o efectividad",
      "Vendedores con múltiples rutas en el mismo período se consolidan en una sola fila con rutas concatenadas y suma de clientes de todas sus rutas",
      "Porcentaje de efectividad calculado sobre el total de clientes activos de la ruta (fuente: dim_cliente_dual)",
      "Dashboard Supervisores: toggle Bs / Uds en toda la sección de detalle por vendedor",
      "Dashboard Supervisores: nueva sección «Liquidaciones» con ventas diarias por vendedor en formato de grilla de fechas",
      "Dashboard Información Rutas: rediseño completo con filtros por marca, día de visita, supervisor y búsqueda de ruta",
      "Dashboard Información Rutas: panel de detalle con ventas por semana, desglose por categoría y top SKUs con cobertura de clientes",
      "Dashboard Información Rutas: botón de descarga del detalle de ruta en Excel",
      "Tendencia Estacional agregado al menú lateral y a los permisos de Gerente de Ventas y Gerente Regional",
    ],
    newDashboardPerms: ["preventas-realizadas", "tendencia-estacional", "informacion-rutas"],
    newDashboardNames: {
      "preventas-realizadas": "Preventas Realizadas",
      "tendencia-estacional": "Tendencia Estacional",
      "informacion-rutas": "Información Rutas",
    },
  },
  {
    version: "1.1.4",
    date: "Mayo 2026",
    fixes: [
      "Nombres de canal en tabla y Excel de Proveedores corregidos (ahora muestra WHS, DTS, PROV, SPM en lugar del nombre largo)",
      "Dashboards ya no muestran ceros al inicio de un nuevo mes: se selecciona automáticamente el período con datos más reciente",
    ],
    features: [
      "Nuevo dashboard «Tendencia Estacional» en Evolución Mes: compara ventas del mes actual contra los mismos meses de años anteriores o los últimos 6 meses",
      "Filtros por Regional, Canal, Gestión y Mes con selector de corte de días (mes completo, hasta hoy, o rango personalizado)",
      "Toggle Bs / Uds y modo Estacional / Últimos 6 meses en Tendencia Estacional",
    ],
    newDashboardPerms: ["tendencia-estacional"],
    newDashboardNames: { "tendencia-estacional": "Tendencia Estacional" },
  },
  {
    version: "1.1.3",
    date: "Abril 2026",
    fixes: [
      "Corregida la Pantalla Blanca (WSoD): se agregó ErrorBoundary global para mostrar un mensaje de error en lugar de pantalla en blanco",
      "Exportación Excel: corregido error 500 causado por column_dimensions incompatible con modo write-only de openpyxl",
      "Exportación Excel: corregido problema de GZipMiddleware que eliminaba el Content-Length y corrompía la descarga en rangos grandes",
      "Toast de descarga ya no desaparece al navegar entre dashboards (movido fuera del árbol de rutas)",
    ],
    features: [
      "Nueva sección «Documentos» en el menú: Dashboard Matriz y Descargar Archivos",
      "Exportación de Ventas Efectivas con Combo Armado a Excel con selector de fechas",
      "Notificación persistente durante la descarga: el archivo se genera en segundo plano y se descarga automáticamente al finalizar",
      "Categoría «Sin Clasificar» en Unidades Vendidas y toggle Bs / Uds global",
      "Logos PNG en login y barra de navegación",
      "Favicon del sistema actualizado al ícono Cruzimex (CRZX.ico)",
    ],
    newDashboardPerms: ["descargas"],
    newDashboardNames: { descargas: "Descargar Archivos" },
  },
  {
    version: "1.1.2",
    date: "Abril 2026",
    fixes: ["Clasificación de productos por categoría ahora usa la columna «línea» del DW (más precisa)", "Redirect al cerrar sesión apunta a la ruta correcta en producción"],
    features: [
      "Unidades por Vendedor-SKU: toggle global Bs / Uds afecta toda la página (tabla de vendedores, gráfico y tabla de SKUs)",
      "Unidades por Vendedor-SKU: gráfico de SKUs muestra barra de Avance y barra de Presupuesto",
      "Unidades por Vendedor-SKU: tabla de SKUs ahora muestra Avance, Presupuesto y Cumplimiento",
      "Dashboard Canales / Regional: toggle Bs / Uds en la sección de SKUs",
      "Dashboard Canales / Regional: columna Presupuesto y Cumplimiento en la tabla de SKUs",
    ],
    newDashboardPerms: [],
    newDashboardNames: {},
  },
  {
    version: "1.1.0",
    date: "Abril 2026",
    fixes: [
      "Corrección del gráfico «Avance vs Presupuesto» en Unidades por Vendedor-SKU (escala incorrecta entre unidades y Bs)",
      "Acceso correcto para Gerentes Generales y Gerentes de Ventas en el dashboard de Unidades por Vendedor-SKU",
      "Cambio de proveedor en los dashboards ya no mantenía datos del proveedor anterior",
    ],
    features: [
      "Nueva sección Proveedores con 5 dashboards (Pepsico, Softys, DMujer, Apego, COLHER): KPIs, ventas por regional, gráfico por canal y tabla detalle con exportación a Excel",
      "Tabla de Vendedores ahora muestra la columna «Venta Bs» con el total monetario por vendedor",
      "Gráfico de SKUs del vendedor ahora refleja Venta Neta en Bs",
      "Indicador de cumplimiento renombrado a «Cumpl.» para mayor claridad (es % vs presupuesto en Bs, no vs unidades)",
      "Footer del sistema con número de versión",
    ],
    newDashboardPerms: ["pepsico", "softys", "dmujer", "apego", "colher"],
    newDashboardNames: {
      pepsico: "Dashboard Pepsico",
      softys: "Dashboard Softys",
      dmujer: "Dashboard DMujer",
      apego: "Dashboard Apego",
      colher: "Dashboard COLHER",
    },
  },
  {
    version: "1.0.0",
    date: "Marzo 2026",
    fixes: [],
    features: ["Lanzamiento inicial del sistema BI Cruzimex"],
    newDashboardPerms: [],
    newDashboardNames: {},
  },
];
